### ISSUE TITLE
Improve Saturation Estimation Speed

### ISSUE THREAD

**Issue by DarioS** [mjdufort/RNAseQC#1]
I am surprised that, for 50 samples, it has taken one hour and is still going. I notice the function uses for loops and I think it would be much faster to use `sapply` or `lapply` instead, since R for loops incur a great performance penalty.

**Comment by mjdufort** [comment]
Thanks, Dario. The default method for `estimate_saturation` uses resampling, which is very time-consuming.  For example, with 50 samples at the default settings, it's sampling the entire gene list 1500 times.  I am sure there is room for speed improvements, though I think the gains from using `apply` variants would be relatively small.  I will do some testing.

FYI, you can get a much faster estimate by setting `method = "division"`.

**Comment by mjdufort** [comment]
Your comment pushed me to do some code profiling, which revealed that a huge amount of the processing time was being consumed by the step where the function tabulates the genes after sampling. By using a matrix and `colTabulate` instead of a recycled vector and `table`, I believe I have sped up the sampling version of the function about 5-fold.

Please let me know if you find any further issues with this function or any others in the package.  Thank you!

**Comment by mjdufort** [comment]
The repo is updated with the new version of the package.  I have added the Rfast package as a dependency in order to use the fast tabulation in `colTabulate`
